### ISSUE TITLE
ImportError: cannot import name 'g2p'

### ISSUE THREAD

**Issue by mattmiranda** [Kyubyong/g2p#2]
Hello, 
Thank you for making this handy package. I installed the package using the setup.py file and tried importing it but I get an import error. 

`>>> from g2p_en import g2p
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/g2p_en/__init__.py", line 1, in <module>
    from g2p import  g2p, Session
ImportError: cannot import name 'g2p'`

I also tried uninstalling the package and installing it again using pip but the problem persisted. Am I doing something wrong?

Thanks in advance. 
Matt

**Comment by ozmig77** [comment]
Hello, found a bug in loading submodules at python3 and now it's fixed.

**Comment by mattmiranda** [comment]
Thank you very much!
